version: '3'

services:
  web:
    build: ./web
    container_name: esi_web
    ports:
      - "8080:80"

  nginx:
    build: ./nginx
    container_name: esi_proxy
    ports:
      - "8888:80"
    depends_on:
      - web
